services:
  - type: web
    name: newscore
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers=2 --threads=2 --timeout=120 --bind=0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false